name: Feature Request
description: I want to work on a new feature.
title: "[Feature Request]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve this project! This project is currently only taking new feature requests from contributors who want to make a PR with their ideas. The backlog of planned features outlined in the roadmap or the open issues here will keep us busy for the foreseeable future.

  - type: checkboxes
    id: already
    attributes:
      label: Already implemented?
      options:
        - label: I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
          required: true
        - label: I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Your Feature Request
      value: "## Is your feature request related to a problem? Please describe.\n\n## Describe the solution you'd like\n\n## Additional context"
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: checkboxes
    id: help
    attributes:
      label: Your help is needed!
      description: This project is ambitious as it is, please contribute.
      options:
        - label: Yes I will work on this in the next few days or weeks.
          required: true
